// src/pages/home/components/component1/Component1.tsx
import styles from './component1.less';
import React from 'react';

/** 
 * 示例代码, 熟悉后请删除
 */
export default function Component1({ data = {} }) {
    
    return (
        <div className={styles.component1}>
            <h1>Subcomponent</h1>
            <ul>
                { data && Object.entries(data).map(([key, value]) => <li key={key}>{key}: {value}</li>) }
            </ul>
        </div>
    );
}

// src/pages/home/components/component1/Component1.vue
/** 
 * 示例代码, 熟悉后请删除
 */
<template>
<div :class="$style.component1">
    <h1>Subcomponent</h1>
    <ul>
        <li v-for="user in users" :key="user.id">
            {{ user }}
        </li>   
    </ul>
</div>
</template>

<script>
export default {
    props: ['users']
};
</script>

<style module src="./component1.less"></style>
