// src/layouts/mainLayout/MainLayout.jsx
import styles from './mainLayout.less';
import React, { Component } from 'react';
import { Switch, Route } from 'react-router-dom';
import lazyload from 'Components/lazyload/Lazyload';
import Header from 'Components/header/Header';
import Footer from 'Components/footer/Footer';

const Home = lazyload(() => import(/* webpackPrefetch: true */ 'Pages/home/Home'));
const NotFound = lazyload(() => import(/* webpackPrefetch: true */ 'Pages/notFound/NotFound'));

/**
 * @desc 页面整体框架组件
 */
export default class MainLayout extends Component {
 
    render() {
        return (
            <div className={styles.mainLayout}>
                <Header />
                <div className={styles.container}>
                    <Switch>
                        <Route exact path="/" component={Home} />
                        <Route path="*" component={NotFound} />
                    </Switch>
                </div>
                <Footer />
            </div>
        );
    }
}

// src/layouts/mainLayout/MainLayout.vue
// import lazyload from 'Components/lazyload/Lazyload';

/**
 * @desc 页面主框架组件
 */
<template>
<div :class="$style.mainLayout">
    <Header />
    <div :class="$style.container">
        <router-view />
    </div>
    <Footer />
</div>
</template>

<script>
import Header from 'Components/header/Header';
import Footer from 'Components/footer/Footer';

export default {
    components: {
        Header,
        Footer
    }
}
</script>

<style module src="./mainLayout.less"></style>
